package com.heying.hrmanager.mapper;

import com.heying.hrmanager.pojo.Attendancestate;
import com.heying.hrmanager.pojo.AttendancestateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttendancestateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int countByExample(AttendancestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int deleteByExample(AttendancestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int insert(Attendancestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int insertSelective(Attendancestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    List<Attendancestate> selectByExample(AttendancestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    Attendancestate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") Attendancestate record, @Param("example") AttendancestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int updateByExample(@Param("record") Attendancestate record, @Param("example") AttendancestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int updateByPrimaryKeySelective(Attendancestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendancestate
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int updateByPrimaryKey(Attendancestate record);
}