package com.heying.hrmanager.mapper;

import com.heying.hrmanager.pojo.Attendanceflowing;
import com.heying.hrmanager.pojo.AttendanceflowingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttendanceflowingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int countByExample(AttendanceflowingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int deleteByExample(AttendanceflowingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int insert(Attendanceflowing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int insertSelective(Attendanceflowing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    List<Attendanceflowing> selectByExample(AttendanceflowingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    Attendanceflowing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") Attendanceflowing record, @Param("example") AttendanceflowingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int updateByExample(@Param("record") Attendanceflowing record, @Param("example") AttendanceflowingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int updateByPrimaryKeySelective(Attendanceflowing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendanceflowing
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    int updateByPrimaryKey(Attendanceflowing record);
}