package com.heying.hrmanager.mapper;

import com.heying.hrmanager.pojo.Employeestate;
import com.heying.hrmanager.pojo.EmployeestateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeestateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    int countByExample(EmployeestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    int deleteByExample(EmployeestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    int insert(Employeestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    int insertSelective(Employeestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    List<Employeestate> selectByExample(EmployeestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    Employeestate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Employeestate record, @Param("example") EmployeestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    int updateByExample(@Param("record") Employeestate record, @Param("example") EmployeestateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    int updateByPrimaryKeySelective(Employeestate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeestate
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    int updateByPrimaryKey(Employeestate record);
}