package com.heying.hrmanager.mapper;

import com.heying.hrmanager.pojo.Recruit;
import com.heying.hrmanager.pojo.RecruitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    int countByExample(RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    int deleteByExample(RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    int insert(Recruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    int insertSelective(Recruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    List<Recruit> selectByExampleWithBLOBs(RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    List<Recruit> selectByExample(RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    Recruit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") Recruit record, @Param("example") RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Recruit record, @Param("example") RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    int updateByExample(@Param("record") Recruit record, @Param("example") RecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    int updateByPrimaryKeySelective(Recruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Recruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit
     *
     * @mbggenerated Tue Dec 11 11:33:08 CST 2018
     */
    int updateByPrimaryKey(Recruit record);
}