package com.heying.hrmanager.mapper;

import com.heying.hrmanager.pojo.Recruitandresume;
import com.heying.hrmanager.pojo.RecruitandresumeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecruitandresumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int countByExample(RecruitandresumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int deleteByExample(RecruitandresumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int insert(Recruitandresume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int insertSelective(Recruitandresume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    List<Recruitandresume> selectByExample(RecruitandresumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    Recruitandresume selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") Recruitandresume record, @Param("example") RecruitandresumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int updateByExample(@Param("record") Recruitandresume record, @Param("example") RecruitandresumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int updateByPrimaryKeySelective(Recruitandresume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruitandresume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int updateByPrimaryKey(Recruitandresume record);
}