package com.heying.hrmanager.mapper;

import com.heying.hrmanager.pojo.Resume;
import com.heying.hrmanager.pojo.ResumeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int countByExample(ResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int deleteByExample(ResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int insert(Resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int insertSelective(Resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    List<Resume> selectByExampleWithBLOBs(ResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    List<Resume> selectByExample(ResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    Resume selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") Resume record, @Param("example") ResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Resume record, @Param("example") ResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int updateByExample(@Param("record") Resume record, @Param("example") ResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int updateByPrimaryKeySelective(Resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    int updateByPrimaryKey(Resume record);
}