package com.heying.hrmanager.mapper;

import com.heying.hrmanager.pojo.Rewardsandpunishments;
import com.heying.hrmanager.pojo.RewardsandpunishmentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RewardsandpunishmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    int countByExample(RewardsandpunishmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    int deleteByExample(RewardsandpunishmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    int insert(Rewardsandpunishments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    int insertSelective(Rewardsandpunishments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    List<Rewardsandpunishments> selectByExample(RewardsandpunishmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    Rewardsandpunishments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Rewardsandpunishments record, @Param("example") RewardsandpunishmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    int updateByExample(@Param("record") Rewardsandpunishments record, @Param("example") RewardsandpunishmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    int updateByPrimaryKeySelective(Rewardsandpunishments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewardsandpunishments
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    int updateByPrimaryKey(Rewardsandpunishments record);
}