package com.heying.hrmanager.pojo;

import java.util.Date;

public class Attendanceflowing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendanceflowing.id
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendanceflowing.employeeid
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    private Integer employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendanceflowing.beginTime
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendanceflowing.endTime
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendanceflowing.state
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendanceflowing.id
     *
     * @return the value of attendanceflowing.id
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendanceflowing.id
     *
     * @param id the value for attendanceflowing.id
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendanceflowing.employeeid
     *
     * @return the value of attendanceflowing.employeeid
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendanceflowing.employeeid
     *
     * @param employeeid the value for attendanceflowing.employeeid
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendanceflowing.beginTime
     *
     * @return the value of attendanceflowing.beginTime
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendanceflowing.beginTime
     *
     * @param begintime the value for attendanceflowing.beginTime
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendanceflowing.endTime
     *
     * @return the value of attendanceflowing.endTime
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendanceflowing.endTime
     *
     * @param endtime the value for attendanceflowing.endTime
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendanceflowing.state
     *
     * @return the value of attendanceflowing.state
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendanceflowing.state
     *
     * @param state the value for attendanceflowing.state
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }
}