package com.heying.hrmanager.pojo;

public class Attendancestate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendancestate.id
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendancestate.state
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendancestate.id
     *
     * @return the value of attendancestate.id
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendancestate.id
     *
     * @param id the value for attendancestate.id
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendancestate.state
     *
     * @return the value of attendancestate.state
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendancestate.state
     *
     * @param state the value for attendancestate.state
     *
     * @mbggenerated Mon Dec 17 09:38:35 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}