package com.heying.hrmanager.pojo;

import java.util.Date;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.id
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.Dept_name
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.createTime
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.id
     *
     * @return the value of dept.id
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.id
     *
     * @param id the value for dept.id
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.Dept_name
     *
     * @return the value of dept.Dept_name
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.Dept_name
     *
     * @param deptName the value for dept.Dept_name
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.createTime
     *
     * @return the value of dept.createTime
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.createTime
     *
     * @param createtime the value for dept.createTime
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}