package com.heying.hrmanager.pojo;

public class Employeebak {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeebak.id
     *
     * @mbggenerated Tue Dec 11 09:45:28 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeebak.reason
     *
     * @mbggenerated Tue Dec 11 09:45:28 CST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeebak.employeeId
     *
     * @mbggenerated Tue Dec 11 09:45:28 CST 2018
     */
    private Integer employeeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeebak.id
     *
     * @return the value of employeebak.id
     *
     * @mbggenerated Tue Dec 11 09:45:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeebak.id
     *
     * @param id the value for employeebak.id
     *
     * @mbggenerated Tue Dec 11 09:45:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeebak.reason
     *
     * @return the value of employeebak.reason
     *
     * @mbggenerated Tue Dec 11 09:45:28 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeebak.reason
     *
     * @param reason the value for employeebak.reason
     *
     * @mbggenerated Tue Dec 11 09:45:28 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeebak.employeeId
     *
     * @return the value of employeebak.employeeId
     *
     * @mbggenerated Tue Dec 11 09:45:28 CST 2018
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeebak.employeeId
     *
     * @param employeeid the value for employeebak.employeeId
     *
     * @mbggenerated Tue Dec 11 09:45:28 CST 2018
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }
}