package com.heying.hrmanager.pojo;

public class Employeestate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeestate.id
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeestate.state
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeestate.id
     *
     * @return the value of employeestate.id
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeestate.id
     *
     * @param id the value for employeestate.id
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeestate.state
     *
     * @return the value of employeestate.state
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeestate.state
     *
     * @param state the value for employeestate.state
     *
     * @mbggenerated Mon Dec 10 17:45:22 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}