package com.heying.hrmanager.pojo;

import java.util.Date;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_name
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gender
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.hirdate
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private Date hirdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.birthdate
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.resumeId
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private Integer resumeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.salary
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private Double salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.stateid
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private Integer stateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.deptId
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.positionId
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    private Integer positionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_name
     *
     * @return the value of employee.emp_name
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_name
     *
     * @param empName the value for employee.emp_name
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gender
     *
     * @return the value of employee.gender
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gender
     *
     * @param gender the value for employee.gender
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.hirdate
     *
     * @return the value of employee.hirdate
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public Date getHirdate() {
        return hirdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.hirdate
     *
     * @param hirdate the value for employee.hirdate
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setHirdate(Date hirdate) {
        this.hirdate = hirdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.birthdate
     *
     * @return the value of employee.birthdate
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.birthdate
     *
     * @param birthdate the value for employee.birthdate
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.resumeId
     *
     * @return the value of employee.resumeId
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public Integer getResumeid() {
        return resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.resumeId
     *
     * @param resumeid the value for employee.resumeId
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setResumeid(Integer resumeid) {
        this.resumeid = resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.salary
     *
     * @return the value of employee.salary
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.salary
     *
     * @param salary the value for employee.salary
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.stateid
     *
     * @return the value of employee.stateid
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public Integer getStateid() {
        return stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.stateid
     *
     * @param stateid the value for employee.stateid
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setStateid(Integer stateid) {
        this.stateid = stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.deptId
     *
     * @return the value of employee.deptId
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.deptId
     *
     * @param deptid the value for employee.deptId
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.positionId
     *
     * @return the value of employee.positionId
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public Integer getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.positionId
     *
     * @param positionid the value for employee.positionId
     *
     * @mbggenerated Mon Dec 10 14:36:45 CST 2018
     */
    public void setPositionid(Integer positionid) {
        this.positionid = positionid;
    }
}