package com.heying.hrmanager.pojo;

import java.util.Date;

public class Recruitandresume {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruitandresume.id
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruitandresume.resumeId
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private Integer resumeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruitandresume.recruitId
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private Integer recruitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruitandresume.interviewTime
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private Date interviewtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruitandresume.consult
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private String consult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruitandresume.entry
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private String entry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruitandresume.id
     *
     * @return the value of recruitandresume.id
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruitandresume.id
     *
     * @param id the value for recruitandresume.id
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruitandresume.resumeId
     *
     * @return the value of recruitandresume.resumeId
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public Integer getResumeid() {
        return resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruitandresume.resumeId
     *
     * @param resumeid the value for recruitandresume.resumeId
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setResumeid(Integer resumeid) {
        this.resumeid = resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruitandresume.recruitId
     *
     * @return the value of recruitandresume.recruitId
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public Integer getRecruitid() {
        return recruitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruitandresume.recruitId
     *
     * @param recruitid the value for recruitandresume.recruitId
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setRecruitid(Integer recruitid) {
        this.recruitid = recruitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruitandresume.interviewTime
     *
     * @return the value of recruitandresume.interviewTime
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public Date getInterviewtime() {
        return interviewtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruitandresume.interviewTime
     *
     * @param interviewtime the value for recruitandresume.interviewTime
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setInterviewtime(Date interviewtime) {
        this.interviewtime = interviewtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruitandresume.consult
     *
     * @return the value of recruitandresume.consult
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public String getConsult() {
        return consult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruitandresume.consult
     *
     * @param consult the value for recruitandresume.consult
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setConsult(String consult) {
        this.consult = consult == null ? null : consult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruitandresume.entry
     *
     * @return the value of recruitandresume.entry
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public String getEntry() {
        return entry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruitandresume.entry
     *
     * @param entry the value for recruitandresume.entry
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setEntry(String entry) {
        this.entry = entry == null ? null : entry.trim();
    }
}