package com.heying.hrmanager.pojo;

import java.util.Date;

public class Recruit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.id
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.publishDate
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    private Date publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.deptId
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.postionId
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    private Integer postionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.postion
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    private String postion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.condition
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    private String condition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.id
     *
     * @return the value of recruit.id
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.id
     *
     * @param id the value for recruit.id
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.publishDate
     *
     * @return the value of recruit.publishDate
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public Date getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.publishDate
     *
     * @param publishdate the value for recruit.publishDate
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public void setPublishdate(Date publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.deptId
     *
     * @return the value of recruit.deptId
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.deptId
     *
     * @param deptid the value for recruit.deptId
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.postionId
     *
     * @return the value of recruit.postionId
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public Integer getPostionid() {
        return postionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.postionId
     *
     * @param postionid the value for recruit.postionId
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public void setPostionid(Integer postionid) {
        this.postionid = postionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.postion
     *
     * @return the value of recruit.postion
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public String getPostion() {
        return postion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.postion
     *
     * @param postion the value for recruit.postion
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public void setPostion(String postion) {
        this.postion = postion == null ? null : postion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.condition
     *
     * @return the value of recruit.condition
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.condition
     *
     * @param condition the value for recruit.condition
     *
     * @mbggenerated Tue Dec 11 11:33:07 CST 2018
     */
    public void setCondition(String condition) {
        this.condition = condition == null ? null : condition.trim();
    }
}