package com.heying.hrmanager.pojo;

import java.util.Date;

public class Resume {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.id
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.name
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.birthday
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.gender
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.education
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.userId
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.experience
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    private String experience;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.id
     *
     * @return the value of resume.id
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.id
     *
     * @param id the value for resume.id
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.name
     *
     * @return the value of resume.name
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.name
     *
     * @param name the value for resume.name
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.birthday
     *
     * @return the value of resume.birthday
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.birthday
     *
     * @param birthday the value for resume.birthday
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.gender
     *
     * @return the value of resume.gender
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.gender
     *
     * @param gender the value for resume.gender
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.education
     *
     * @return the value of resume.education
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.education
     *
     * @param education the value for resume.education
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.userId
     *
     * @return the value of resume.userId
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.userId
     *
     * @param userid the value for resume.userId
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.experience
     *
     * @return the value of resume.experience
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.experience
     *
     * @param experience the value for resume.experience
     *
     * @mbggenerated Thu Dec 13 09:42:20 CST 2018
     */
    public void setExperience(String experience) {
        this.experience = experience == null ? null : experience.trim();
    }
}