package com.heying.hrmanager.pojo;

import java.util.Date;

public class Rewardsandpunishments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewardsandpunishments.id
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewardsandpunishments.Rewardsandpunishmentstime
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    private Date rewardsandpunishmentstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewardsandpunishments.reason
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewardsandpunishments.money
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewardsandpunishments.employeeId
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    private Integer employeeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewardsandpunishments.id
     *
     * @return the value of rewardsandpunishments.id
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewardsandpunishments.id
     *
     * @param id the value for rewardsandpunishments.id
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewardsandpunishments.Rewardsandpunishmentstime
     *
     * @return the value of rewardsandpunishments.Rewardsandpunishmentstime
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    public Date getRewardsandpunishmentstime() {
        return rewardsandpunishmentstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewardsandpunishments.Rewardsandpunishmentstime
     *
     * @param rewardsandpunishmentstime the value for rewardsandpunishments.Rewardsandpunishmentstime
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    public void setRewardsandpunishmentstime(Date rewardsandpunishmentstime) {
        this.rewardsandpunishmentstime = rewardsandpunishmentstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewardsandpunishments.reason
     *
     * @return the value of rewardsandpunishments.reason
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewardsandpunishments.reason
     *
     * @param reason the value for rewardsandpunishments.reason
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewardsandpunishments.money
     *
     * @return the value of rewardsandpunishments.money
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewardsandpunishments.money
     *
     * @param money the value for rewardsandpunishments.money
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewardsandpunishments.employeeId
     *
     * @return the value of rewardsandpunishments.employeeId
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewardsandpunishments.employeeId
     *
     * @param employeeid the value for rewardsandpunishments.employeeId
     *
     * @mbggenerated Mon Dec 24 08:06:09 CST 2018
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }
}